const defaultButtonConfig = {
  color: '#666666',
  width: '80px',
  height: '25px',
  iconWidth: '16px',
  iconHeight: '16px',
  backgroundColor: 'white',
  border: '1px solid rgb(204, 204, 204)',
  borderRadius: '6px',
  hover: {
    color: 'white',
    backgroundColor: '#666666',
  },
};

export const KbButtonConfig = {
  deleteButton: {
    text: '삭제',
    color: 'red',
    width: '80px',
    height: '25px',
    iconWidth: '16px',
    iconHeight: '16px',
    backgroundColor: 'white',
    border: '1px solid red',
    borderRadius: '6px',
    hover: {
      color: 'white',
      backgroundColor: 'red',
    },
  },
  addButton: {
    text: '추가',
    color: 'rgb(0, 56, 121)',
    width: '80px',
    height: '25px',
    iconWidth: '16px',
    iconHeight: '16px',
    backgroundColor: 'white',
    border: '1px solid rgb(0, 56, 121)',
    borderRadius: '6px',
    hover: {
      color: 'white',
      backgroundColor: 'rgb(0, 56, 121)',
    },
  },
  saveButton: {
    text: '저장',
    color: 'rgb(0, 56, 121)',
    width: '80px',
    height: '25px',
    iconWidth: '16px',
    iconHeight: '16px',
    backgroundColor: 'white',
    border: '1px solid rgb(0, 56, 121)',
    borderRadius: '6px',
    hover: {
      color: 'white',
      backgroundColor: 'rgb(0, 56, 121)',
    },
  },
  updateButton: {
    text: '수정',
    color: 'green',
    width: '80px',
    height: '25px',
    iconWidth: '16px',
    iconHeight: '16px',
    backgroundColor: 'white',
    border: '1px solid green',
    borderRadius: '6px',
    hover: {
      color: 'white',
      backgroundColor: 'green',
    },
  },
  searchButton: {
    text: '검색',
    color: '#666666',
    width: '80px',
    height: '25px',
    iconWidth: '16px',
    iconHeight: '16px',
    backgroundColor: 'white',
    border: '1px solid rgb(204, 204, 204)',
    borderRadius: '6px',
    hover: {
      color: 'white',
      backgroundColor: '#666666',
    },
  },
  closeButton: {
    text: '닫기',
    color: '#666666',
    width: '80px',
    height: '25px',
    iconWidth: '16px',
    iconHeight: '16px',
    backgroundColor: 'white',
    border: '1px solid rgb(204, 204, 204)',
    borderRadius: '6px',
    hover: {
      color: 'white',
      backgroundColor: '#666666',
    },
  },
  closeTextButton: {
    text: '',
    color: '#666666',
    width: '80px',
    height: '25px',
    iconWidth: '16px',
    iconHeight: '16px',
    backgroundColor: 'white',
    border: '1px solid rgb(204, 204, 204)',
    borderRadius: '6px',
    hover: {
      color: 'white',
      backgroundColor: '#666666',
    },
  },
  initButton: {
    text: '',
    color: '#666666',
    width: '80px',
    height: '25px',
    iconWidth: '16px',
    iconHeight: '25px',
    backgroundColor: 'white',
    border: '1px solid rgb(204, 204, 204)',
    borderRadius: '6px',
    hover: {
      color: 'white',
      backgroundColor: '#666666',
    },
  },
};
